### ISSUE TITLE
bluez

### ISSUE THREAD

**Issue by stauraum** [klein0r/fhem-docker#6]
Hello,

Nice work!

please add bluez to your fhem-Dockerfile. I'm using it for presence.

Thanks.

**Comment by hvorragend** [comment]
Das Ticket wurde zwar schon geschlossen, aber ich will dennoch etwas dazu beitragen.
Kann es sein, dass das auch überhaupt nicht funktioniert hätte?
Der FHEM-Container läuft hier im Bridge-Modus und soweit ich weiß müssen für leprecensed & Co. die Bluetooth-Treiber im Host-Modus laufen. Bluetooth-Dongles werden, glaube ich, nicht an die Container weitergereicht. Auch nicht mit --device.

Auch habe ich es nicht geschafft, die Container mit Alpine, Baseimage & Co. zu erstellen. Also musste das große Debian daran glauben:

**Dockerfile**
```
FROM debian:stretch

ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm

RUN apt-get update && apt-get -y install \
    perl \
    libnet-server-perl \
    libusb-1.0-0-dev \
    bluetooth \
    bluez \
    blueman \
    tzdata \
    bluez-hcidump \
    wget && \
    apt-get clean && cd / && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Zeitzone einstellen
RUN echo "Europe/Berlin" > /etc/timezone && dpkg-reconfigure tzdata

WORKDIR "/opt"

# RUN wget https://github.com/mhop/fhem-mirror/raw/master/fhem/contrib/PRESENCE/lepresenced && \
#    chmod +x lepresenced && \
#    chgrp -cR dialout lepresenced

EXPOSE 5333

COPY lepresenced /opt/lepresenced
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x lepresenced && \
    chgrp -cR dialout lepresenced
```


**docker-compose.yml**
```
  lepresenced:
        container_name: lepresenced
        restart: unless-stopped
        expose:
            - "5333"
        build: lepresenced
        privileged: true
        volumes:
             - /etc/localtime:/etc/localtime:ro
        network_mode: "host"
```
